### ISSUE TITLE
_performAnswerCallAction not called

### ISSUE THREAD

**Issue by ravivlb** [peerwaya/flutter_call_kit#10]
When answering the call, I have to implement my own flow. but the event not calling back.

Please help to resolve this.

**Comment by yukitaka13-1110** [comment]
@ravivlb Do you use the latest version?

**Comment by ravivlb** [comment]
Latest version only. I have to retry again.

**Comment by yukitaka13-1110** [comment]
@ravivlb Dart pub's latest version is v0.0.2.
https://github.com/peerwaya/flutter_call_kit/blob/master/CHANGELOG.md
So you should write in `pubspec.yaml` like the following.
```
flutter_call_kit:
    git:
      url: git://github.com/peerwaya/flutter_call_kit.git
      ref: master
```
